# Generated by Django 3.2.8 on 2021-10-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=150)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
