# Generated by Django 3.2.8 on 2021-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('fid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flightnumber', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('accept', models.BooleanField()),
                ('username', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=150)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('pnr', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'flight',
                'managed': True,
            },
        ),
    ]
