# Generated by Django 3.2.8 on 2021-11-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0002_customer_location_schedule_ticket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
