# Generated by Django 3.2.8 on 2021-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0004_rename_dob_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='airport_thai',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='city_thai',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
