# Generated by Django 3.2.8 on 2021-11-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0005_auto_20211104_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='economy_class',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_class',
            field=models.FloatField(null=True),
        ),
    ]
