# Generated by Django 3.2.8 on 2021-11-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0006_auto_20211104_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='economy_class',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='first_class',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('first', 'First')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
